### PR TITLE
Enable multiple blobs for SoA mapping

### PR DESCRIPTION
**Pull request by bernhardmgruber**
A multi-blob version of the SoA mapping allows one blob per datum domain attribute.

### CODE REVIEW

**Comment by bussmann** [comment]
What is a blob?

**Comment by psychocoderHPC** [comment]
image
Called: blob fish :smile:

**Comment by bussmann** [comment]
Now I want multiple of these! Make it happen!

**Comment by bernhardmgruber** [comment]
> What is a blob?

I simple search engine query could have answered that: A blob is a Binary large object.
Blobs are also described in the LLAMA documentation: https://llama-doc.readthedocs.io/en/latest/pages/blobs.html

Please also refrain from posting pictures of depressurized animals, even though the might look funny to someone ;)

**Pull request merged**
